CREATE TABLE "BlogCategory" (
    "id" SERIAL NOT NULL,
    "legacyId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BlogCategory_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "BlogCategory_legacyId_key" ON "BlogCategory"("legacyId");
CREATE INDEX "BlogCategory_isActive_sortOrder_idx" ON "BlogCategory"("isActive", "sortOrder");

ALTER TABLE "BlogPost" ADD COLUMN "blogCategoryId" INTEGER;
CREATE INDEX "BlogPost_blogCategoryId_idx" ON "BlogPost"("blogCategoryId");

INSERT INTO "BlogCategory" ("legacyId", "name", "sortOrder", "updatedAt") VALUES
    (1, 'Unityverse Academy Blog', 1, CURRENT_TIMESTAMP),
    (2, 'Popüler Yazılar', 2, CURRENT_TIMESTAMP),
    (3, 'Sektörde Merak Edilenler', 3, CURRENT_TIMESTAMP),
    (4, 'Sektörden Tasarım Haberleri', 4, CURRENT_TIMESTAMP),
    (5, 'Dijital Oyun Haberleri', 5, CURRENT_TIMESTAMP),
    (6, 'Yazılım Alanında En Güncel Yazılar', 6, CURRENT_TIMESTAMP),
    (7, 'Dünya''dan Haberler', 7, CURRENT_TIMESTAMP),
    (8, 'Dünya''dan Kültür Sanat Haberleri', 8, CURRENT_TIMESTAMP),
    (9, 'Sektörde Merak Edilenler', 9, CURRENT_TIMESTAMP),
    (10, 'ÇALIŞMA HAYATINA ATILAN MEZUNLARIMIZIN BAŞARI HİKAYELERİ', 10, CURRENT_TIMESTAMP),
    (11, 'Grafik Tasarım', 11, CURRENT_TIMESTAMP),
    (12, 'Mimarlık Eğitimleri', 12, CURRENT_TIMESTAMP);

WITH mapping("slug", "legacyId") AS (
  VALUES
    ('3b-modelleme-egitimleri-zbrush-ileri-seviye-284', 1),
    ('3ds-max-egitimi-uv-mapping-ve-kaplama-yonetimi-305', 1),
    ('3dsmax-kursu-294', 1),
    ('adobe-indesign-kursu-egitimi-mizanpaj-tasarimi-288', 11),
    ('after-effects-egitimi-adobe-after-effects-ile-motion-graphicse-giris-309', 11),
    ('after-effects-egitimi-sinematik-vfx-uretimi-307', 11),
    ('apple-guclu-yeni-nesil-apple-tv-4kyi-tanitiyor-53', 7),
    ('apple-usb-c-gecisine-hazirlaniyor-aksesuarlar-da-guncellenecek-58', 7),
    ('aranan-3d-artist-olma-yaratici-yeteneginizi-zirveye-tasiyin-164', 2),
    ('arda-bickinnin-yazilim-test-otomasyonu-egitimi-ve-testiniumdaki-staj-sureci-89', 10),
    ('autocad-egitimi-autocadde-mimari-plan-cizimi-300', 12),
    ('autocad-egitimi-statik-projelerde-autocad-kullanimi-299', 12),
    ('autocad-kursu-291', 12),
    ('autocad-kursu-egitimi-autocadde-parametrik-cizim-mantigi-298', 12),
    ('autodesk-fusion-360-kursu-egitimi-271', 12),
    ('basari-hikâyesi-buse-sahinoglunun-eczacibasindaki-3d-tasarim-yolculugu-107', 10),
    ('basari-hikâyesi-gokce-yilmaz-barunun-shopcutebutcreepy-markasiyla-girisimcilik-yolculugu-109', 10),
    ('basari-hikâyesi-gulsah-temelin-eczacibasindaki-3ds-max-tasarim-yolculugu-106', 10),
    ('basari-hikâyesi-melike-cetinin-lc-waikikideki-doku-kaplama-ve-desen-tasarimi-yolculugu-105', 10),
    ('baski-ve-dijital-grafikler-arasindaki-farklar-nelerdir-79', 3),
    ('batuhan-kocakin-basari-hikayesi-unityverse-academy-ile-vfx-uzmanligina-giden-yol-207', 10),
    ('beginning-graphic-design-images-74', 3),
    ('begum-kiroglunun-grafik-tasarim-ve-video-kurgu-alanindaki-yolculugu-98', 10),
    ('berkay-kurt-multiplayer-oyun-gelistiriciliginde-bir-yildiz-130', 10),
    ('bir-grafik-tasarimci-renk-psikolojisini-nasil-etkin-kullanabilir-77', 3),
    ('blender-egitimi-3d-modelleme-animasyon-ve-render-rehberi-280', 1),
    ('blender-egitimi-blender-profesyonel-kullanim-rehberi-308', 1),
    ('blender-ile-3d-oyun-modelleme-son-teknolojilerle-gercekci-oyun-dunyalari-yaratin-132', 5),
    ('burak-ercayanin-yazilim-test-otomasyonu-egitimi-ve-testiniumdaki-isi-88', 10),
    ('can-kalyoncuoglu-hayallerden-gerceklere-128', 10),
    ('cizgi-film-ve-animasyon-egitiminde-son-egilimler-11', 4),
    ('cv-hazirlama-rehberi-etkili-bir-ozgecmis-icin-tum-adimlar-112', 2),
    ('desinatorluk-ve-moda-tasarimi-yaraticiliginizi-dijital-dunyada-hayata-gecirin-158', 4),
    ('dijital-oyun-tasarimi-bolumu-bilgiyi-ticarilestirme-merkezi-is-birligiyle-lootjam-gerceklestirdi-314', 1),
    ('elif-arslanin-yazilim-gelistirici-olarak-ayakkabi-dunyasindaki-baslangici-94', 10),
    ('elon-musk-twitterin-kontrolunu-ele-gecirdi-66', 7),
    ('emre-gungorun-sps-senurdaki-robotic-system-developer-yolculugu-95', 10),
    ('enes-bugra-cengizin-full-stack-developer-yolculugu-93', 10),
    ('evden-calisarak-ek-gelir-elde-etmek-icin-grafik-tasarim-ve-video-kurgu-firsatlari-111', 2),
    ('fatih-yilmazin-yazilim-yolculugu-ve-lufthansadaki-basarisi-91', 10),
    ('filiz-tumuklunun-yazilim-test-otomasyonu-egitimi-ve-kariyer-basarisi-90', 10),
    ('film-ve-animasyon-icin-storyboard-yapay-zeka-destekli-egitimlerle-yaratici-surecte-yeni-bir-donem-157', 3),
    ('flutter-ile-mobil-uygulama-gelistirme-hizli-verimli-ve-platformlar-arasi-uygulamalar-153', 5),
    ('fusion-360-egitimi-293', 12),
    ('fusion-360-kursu-egitimi-274', 2),
    ('gencler-haber-almak-icin-tiktok-ve-instagrama-yoneliyor-29', 2),
    ('gorkem-tekinin-vakif-katilimdaki-backend-developer-yolculugu-96', 10),
    ('grafik-tasarim-egitimleri-adobe-after-effects-ileri-seviye-283', 11),
    ('grafik-tasarim-kursu-egitimi-289', 11),
    ('green-card-basvurusu-nasil-ve-nereden-yapilir-basvuru-sartlari-nelerdir-ucretli-mi-green-card-basvurusu-icin-pasaport-ve-ingilizce-dil-bilgisi-gerekiyor-mu-54', 7),
    ('haber-almanin-yeni-adresi-tiktok-60', 7),
    ('herkes-yaratici-olabilir-72', 3),
    ('iklim-aktivistleri-van-goghun-unlu-tablosuna-domates-corbasi-firlatti-49', 7),
    ('is-basvurularinda-red-almanizin-arkasindaki-nedenler-ve-basari-icin-yapilacak-adimlar-110', 2),
    ('kadinlarin-katiliminin-getirdigi-basari-hikayeleri-102', 2),
    ('kadinlarin-yazilim-sektorunde-yer-almasi-gelecegi-sekillendiren-guc-103', 2),
    ('karanliktan-aydinliga-diwali-instagram-etkinligi-61', 7),
    ('kod-gelistirmenin-otesinde-yapay-zeka-egitimi-213', 6),
    ('mario-animasyon-filmi-geliyor-50', 7),
    ('marvelous-designer-ile-giysi-tasarimi-uzmanligi-148', 4),
    ('matematik-ne-ise-yarar-57', 2),
    ('maya-egitimi-285', 1),
    ('meslek-sahipleri-yapay-zekâya-entegre-olacak-cetin-kaya-koc-ile-soylesi-28', 2),
    ('metaverse-dijital-evrende-yukselen-firsatlar-ve-gelecegin-teknolojisi-154', 2),
    ('metaverseu-en-iyi-anlatan-5-film-56', 7),
    ('mevcut-sartlarda-istanbulda-is-bulma-imkanlari-87', 2),
    ('mezunumuz-burak-yilmazin-basari-hikayesi-265', 10),
    ('mimarlik-egitimleri-3ds-max-ile-mimarlik-312', 12),
    ('oguzhan-durakin-grafik-tasarim-ve-video-kurgu-alanindaki-yolculugu-100', 10),
    ('osman-derebasinin-grafik-tasarim-ve-video-kurgu-alanindaki-yolculugu-101', 10),
    ('otonom-surus-teknolojileri-yazilim-teknolojilerini-birlestiren-guc-219', 6),
    ('oyun-gelistirme-egitimi-2025-oyun-gelistirme-ve-kullanilan-teknolojiler-208', 5),
    ('oyun-gelistirme-egitimi-oyun-motorlarinin-evrimi-227', 5),
    ('oyun-gelistirme-egitimi-unity-ve-c-ile-kendi-oyununuzu-gelistirin-216', 6),
    ('oyun-gelistirme-egitimleri-unity-egitimi-238', 5),
    ('oyun-gelistirme-unityde-yapay-zekâ-ile-karakter-davranisi-olusturma-210', 5),
    ('oyunlarda-yapay-zekâ-ve-metaverse-iliskisi-209', 5),
    ('perspektif-75', 3),
    ('photoshop-egitimi-actions-olusturma-ve-kullanma-310', 11),
    ('photoshop-egitimi-lens-flare-bokeh-ve-cinematic-efektler-olusturma-304', 11),
    ('photoshop-egitimi-photoshop-ile-uiux-tasarimi-303', 11),
    ('photoshop-egitimi-photoshopta-akilli-nesneler-302', 11),
    ('photoshop-egitimi-photoshopta-atmosfer-efektleri-306', 11),
    ('photoshop-egitimi-photoshopta-profesyonel-fotograf-duzenleme-teknikleri-301', 11),
    ('photoshop-kursu-egitimi-297', 11),
    ('renk-teorisi-73', 9),
    ('revit-egitimi-revit-ile-mimarlik-311', 12),
    ('revit-kursu-egitimi-273', 12),
    ('revit-kursu-egitimi-275', 12),
    ('revit-kursu-egitimi-290', 12),
    ('semantik-teknoloji-depo-stok-takip-uygulamasi-tanitimi-251', 1),
    ('siber-guvenlik-egitimleri-siber-guvenlik-uzmani-olmak-icin-bilmen-gerekenler-221', 3),
    ('siber-guvenlik-egitimleri-sifirinci-gun-acigi-222', 9),
    ('siber-guvenlik-uzmanligi-ve-ethical-hacking-dijital-guvenligin-korumacisi-olmaya-hazirlanin-160', 3),
    ('sketchup-kursu-292', 12),
    ('solidworks-ile-endustriyel-urun-tasarimi-uzmanligi-162', 3),
    ('suat-erizin-ayes-celikteki-yazilim-gelistirici-ve-kalite-kontrol-gorevi-97', 10),
    ('substance-painter-egitimi-286', 1),
    ('suleyman-ozgonul-oyun-gelistiricilikte-zirveye-giden-yol-129', 10),
    ('turkiye-rekabet-kurulu-metaya-ceza-kesti-64', 7),
    ('unity-ile-oyun-gelistirme-egitimi-detayli-rehberle-kendi-oyunlariniza-yon-verin-142', 5),
    ('unityverse-academy-mezunu-turgay-sefa-sarigedikin-basari-hikâyesi-313', 1),
    ('unreal-engine-5-ile-blueprint-oyun-gelistirme-131', 5),
    ('unreal-engine-egitimi-295', 1),
    ('unreal-engine-egitimi-unreal-engine-havacilik-sektoru-uygulamalari-245', 1),
    ('unreal-engine-egitimi-virtual-production-cinematics-287', 5),
    ('unreal-engine-egitimleri-artirilmis-gerceklik-ile-pilot-egitimi-246', 7),
    ('unreal-engine-egitimleri-oyun-programlamaya-bakis-243', 5),
    ('unreal-engine-hakkinda-her-sey-67', 5),
    ('uretilen-ilk-iphone-rekor-bir-fiyata-satildi-55', 7),
    ('uretken-yapay-zeka-yazilim-egitimi-214', 6),
    ('web-programlama-egitimi-react-19-231', 6),
    ('web-programlama-egitimleri-kriptografinin-uygulanmasi-230', 6),
    ('web-programlama-egitimlerikriptografi-ve-web-229', 6),
    ('web-tasarim-ragbet-goruyor-76', 3),
    ('yapay-zeka-ve-makine-ogrenmesi-yazilimla-uyumlu-uygulamalar-163', 3),
    ('yazilim-egitimleri-microservices-mimarisi-223', 6),
    ('yazilim-egitimleri-surdurulebilir-yazilim-green-coding-224', 6),
    ('yazilim-egitimleriblockchainin-yeni-uygulamalari-228', 6),
    ('yazilim-gelistirme-egitimi-web-performansi-ve-core-web-vitals-225', 6),
    ('yazilim-gelistirme-egitimleri-api-ve-yapay-zeka-kullanimi-218', 6),
    ('yonetmenlik-ve-sinematografiye-giris-sinema-sanatinda-profesyonellige-adim-atin-146', 3),
    ('zbrush-kursu-egitimi-296', 1)
)
UPDATE "BlogPost" AS post
SET "blogCategoryId" = category."id"
FROM mapping, "BlogCategory" AS category
WHERE post."slug" = mapping."slug"
  AND category."legacyId" = mapping."legacyId";

ALTER TABLE "BlogPost"
ADD CONSTRAINT "BlogPost_blogCategoryId_fkey"
FOREIGN KEY ("blogCategoryId") REFERENCES "BlogCategory"("id")
ON DELETE RESTRICT ON UPDATE CASCADE;
